"""
Logistic Regression – Prediction Script
=======================================

This script loads a trained multiclass logistic regression model, applies it to
a test dataset, and generates predictions for each student’s Hogwarts house.
The model parameters must be stored in a JSON file generated by the training
program.

Main Features
-------------
- Reads a dataset containing the three required numerical features defined in
  the `config` module.
- Loads the logistic regression model weights (θ, means, stds) from a JSON file.
- Uses the function `Predict()` to compute class probabilities and assign the
  most probable house.
- Saves the predictions to a CSV file (`houses.csv`).
- Optionally compares the custom logistic regression model with a scikit-learn
  model if the `--test` flag is supplied.

Command-line Arguments
----------------------
test_file : str
    Path to the dataset to classify.

--jsonpath : str, optional (default: 'weights.json')
    Path to the JSON file generated by the training script containing model weights.

--train_file : str, optional (default: 'datasets/dataset_train.csv')
    Training dataset used only when performing comparison tests.

--test, -t : flag
    If specified, compares the custom model against a scikit-learn model using
    the `compare_models()` function.

Behaviour
---------
1. Handles SIGINT and SIGTERM to ensure a clean shutdown.
2. Reads the test dataset using `read_file()`.
3. Loads the model weights from the specified JSON file.
4. Predicts the Hogwarts house for each row.
5. Writes the results to `houses.csv`.
6. If `--test` is passed:
       - Loads the training dataset.
       - Runs a comparison between the manual and scikit-learn implementations.

Error Handling
--------------
The script terminates with a descriptive error message in the following cases:
- Invalid or unreadable JSON path.
- Failure to read the test or training dataset.
- Exceptions raised by the `Predict()` function (invalid model data,
  malformed input DataFrame, missing features, numeric issues, etc.)

Usage Example
-------------
    python3 logreg_predict.py datasets/dataset_test.csv

    python3 logreg_predict.py datasets/dataset_test.csv \
        --jsonpath model_weights.json \
        --test

Output
------
Produces a file named `houses.csv` containing one predicted house per row,
aligned to the index of the input dataset.
"""

import argparse
import signal
import os
from utils.utils import termination_handler, read_file
from logistic_regression.predict import Predict
from test.prediction import compare_models

def arguments_configuration():
    parser = argparse.ArgumentParser(
        prog='Logistic regression predict',
        description='Given a dataset path, the program will predict the Howarts House students belong throught a multi-classifier model'
    )

    parser.add_argument('test_file')
    parser.add_argument('--jsonpath', default='weights.json', help='Path to json file gene3rated by trainer programm')
    parser.add_argument('--train_file', default='datasets/dataset_train.csv', help='Path to the train dataset')
    parser.add_argument('--test', '-t', action='store_true', help='Compare the results of the manual model to the scikit-learn mkodel')


    return parser.parse_args()

if __name__ == "__main__":
    signal.signal(signal.SIGINT, termination_handler)
    signal.signal(signal.SIGTERM, termination_handler)
    args = arguments_configuration()

    try:
        jsonpath = os.path.abspath(args.jsonpath)
    except Exception as e: 
        print(f'An exception type {type(e).__name__} has ocurred, please check the json file {args.jsonpath}')

    df_predict = read_file(args.test_file)
    prediction = Predict(df_predict, jsonpath)
    prediction.to_csv('houses.csv', index=True)

    if args.test:
        df_train = read_file(args.train_file)
        compare_models(df_predict, df_train, prediction)